
CREATE TABLE EINJURY_01REF (
DiagnosisCodeDescr VARCHAR(255),
eInjury_01 VARCHAR(255)
);

CREATE TABLE EPROCEDURES_03REF (
ProcedureCodeDescr VARCHAR(255),
eProcedures_03 VARCHAR(255)
);

CREATE TABLE ESITUATION_09REF (
eSituation_09 VARCHAR(255),
DiagnosisCodeDescr VARCHAR(255)
);

CREATE TABLE ESITUATION_10REF (
eSituation_10 VARCHAR(255),
DiagnosisCodeDescr VARCHAR(255)
);

CREATE TABLE ESITUATION_11REF (
eSituation_11 VARCHAR(255),
DiagnosisCodeDescr VARCHAR(255)
);

CREATE TABLE ESITUATION_12EF (
eSituation_12 VARCHAR(MAX),
DiagnosisCodeDescr VARCHAR(255)
);

CREATE TABLE FACTPCRADDITIONALRESPONSEMODE (
PerKey INT NOT NULL PRIMARY KEY,
eResponse_24 VARCHAR(255) 
);

CREATE TABLE FACTPCRADDITONALSYMPTOM (
PerKey INT NOT NULL PRIMARY KEY,
eSituation_10 VARCHAR(255)
);

CREATE TABLE FACTPCRADDITONALTRANSPORTMODE (
PerKey INT NOT NULL PRIMARY KEY,
eDisposition_18 VARCHAR(255)
);

CREATE TABLE FACTPCRALCOHOLDRUGUSEINDICATOR (
PerKey INT NOT NULL PRIMARY KEY,
eHistory_17 VARCHAR(255)
);

CREATE TABLE FACTPCRARRESTCPRPROVIDED (
PerKey INT NOT NULL PRIMARY KEY,
eArrest_09 VARCHAR(255)
);

CREATE TABLE FACTPCRARRESTRHYTHMDESTINATION (
eArrest_17 VARCHAR(255)
);

CREATE TABLE FACTPCRARRESTROSC (
PerKey INT NOT NULL PRIMARY KEY,
eArrest_12 VARCHAR(255)
);

CREATE TABLE FACTPCRARRESTWITNESS (
PerKey INT NOT NULL PRIMARY KEY,
eArrest_04 VARCHAR(255)
);

CREATE TABLE FACTPCRBARRIERTOCARE (
PerKey INT NOT NULL PRIMARY KEY,
eHistory_01 VARCHAR(255)
);

CREATE TABLE FACTPCRCAUSEOFINJURY (
PerKey INT NOT NULL PRIMARY KEY,
eInjury_01 VARCHAR(255)
);

CREATE TABLE FACTPCRDESTINATIONREASON (
PerKey INT NOT NULL PRIMARY KEY,
eDisposition_20 VARCHAR(255)
);

CREATE TABLE FACTPCRDESTINATIONTEAM (
PerKey INT NOT NULL PRIMARY KEY,
eDisposition_24 VARCHAR(255),
eDisposition_25 smalldatetime,
);

CREATE TABLE FACTPCRDISPATCHDELAY (
PerKey INT NOT NULL PRIMARY KEY,
eResponse_08 VARCHAR(255)
);

CREATE TABLE FACTPCRINJURYRISKFACTOR (
PerKey INT NOT NULL PRIMARY KEY,
eInjury_04 VARCHAR(255)
);

CREATE TABLE FACTPCRMEDICATION (
PerKey INT NOT NULL PRIMARY KEY,
PcrMedicationKey int,
eMedications_01 smalldatetime,
eMedications_02 VARCHAR(255),
eMedications_03 VARCHAR(255),
eMedications_05 VARCHAR(255),
eMedications_06 VARCHAR(255),
eMedications_07 VARCHAR(255),
eMedications_10 VARCHAR(255),
eMedications_03Descr VARCHAR(255)
);

CREATE TABLE FACTPCRPRIMARYIMPRESSION (
PerKey INT NOT NULL PRIMARY KEY,
eSituation_11 VARCHAR(255)
);

CREATE TABLE FACTPCRPRIMARYSYMPTOM (
PerKey INT NOT NULL PRIMARY KEY,
eSituation_09 VARCHAR(255)
);

CREATE TABLE FACTPCRPROCEDURE (
PerKey INT NOT NULL PRIMARY KEY,
PcrProcedureKey INT,
eProcedures_01 smalldatetime,
eProcedures_02 VARCHAR(255),
eProcedures_03 VARCHAR(255),
eProcedures_05 VARCHAR(255),
eProcedures_06 VARCHAR(255),
eProcedures_08 VARCHAR(255),
eProcedures_10 VARCHAR(255)
);

CREATE TABLE FACTPCRPROTOCOL (
PerKey INT NOT NULL PRIMARY KEY,
eProtocol_01 VARCHAR(255),
eProtocol_02 VARCHAR(255)
);

CREATE TABLE FACTPCRRESPONSEDELAY (
PerKey INT NOT NULL PRIMARY KEY,
eResponse_09 VARCHAR(255)
);

CREATE TABLE FACTPCRSCENEDELAY (
PerKey INT NOT NULL PRIMARY KEY,
eResponse_10 VARCHAR(255)
);

CREATE TABLE FACTPCRSECONDARYIMPRESSION (
PerKey INT NOT NULL PRIMARY KEY,
eSituation_12 VARCHAR(255)
);

CREATE TABLE FACTPCRTRANSPORTDELAY (
PerKey INT NOT NULL PRIMARY KEY,
eSituation_11 VARCHAR(255)
); 

CREATE TABLE FACTPCRTRAUMACRITERIA (
PerKey INT NOT NULL PRIMARY KEY,
eInjury_03 VARCHAR(255)
);

CREATE TABLE FACTPCRTURNAROUNDDELAY (
PerKey INT NOT NULL PRIMARY KEY,
eResponse_12 VARCHAR(255)
);

CREATE TABLE FACTPCRVITAL (
PerKey INT NOT NULL PRIMARY KEY,
PcrVitalKey int,
eVitals_01 smalldatetime,
eVitals_02 VARCHAR(255),
eVitals_04 VARCHAR(255),
eVitals_06 VARCHAR(255),
eVitals_08 VARCHAR(255),
eVitals_10 VARCHAR(255),
eVitals_12 VARCHAR(255),
eVitals_14 VARCHAR(255),
eVitals_16 VARCHAR(255),
eVitals_18 VARCHAR(255),
eVitals_19 VARCHAR(255),
eVitals_20 VARCHAR(255),
eVitals_21 VARCHAR(255),
eVitals_26 VARCHAR(255),
eVitals_27 VARCHAR(255),
eVitals_29 VARCHAR(255),
eVitals_30 VARCHAR(255),
eVitals_31 VARCHAR(255)
);

CREATE TABLE FACTPCRWORKRELATEDEXPOSURE (
PerKey INT NOT NULL PRIMARY KEY,
eOther_05  VARCHAR(255),
);

CREATE TABLE PUB_PCREVENTS (
PerKey INT NOT NULL PRIMARY KEY,
eArrest_01 VARCHAR(255),
eArrest_02 VARCHAR(255), 
eArrest_05 VARCHAR(255),
eArrest_07 VARCHAR(255),
eArrest_14 smalldatetime,
eArrest_16 VARCHAR(255),
eArrest_18 VARCHAR(255),
eDispatch_01 VARCHAR(255),
eDispatch_02 VARCHAR(255),
eDisposition_12 VARCHAR(255),
eDisposition_16 VARCHAR(255),
eDisposition_17 VARCHAR(255),
eDisposition_19 VARCHAR(255),
eDisposition_21 VARCHAR(255),
eDisposition_22 VARCHAR(255),
eDisposition_23 VARCHAR(255),
eOutcome_01 VARCHAR(255),
eOutcome_02 VARCHAR(255),
ePatient_13 VARCHAR(255),
ePatient_15 INT,
ePatient_16 INT,
ePayment_01 VARCHAR(255),
ePayment_50 VARCHAR(255),
eResponse_05 VARCHAR(255),
eResponse_07 VARCHAR(255),
eScene_09 VARCHAR(255),
eSituation_01 smalldatetime,
eSituation_02 VARCHAR(255),
eSituation_07 VARCHAR(255),
eSituation_08 VARCHAR(255),
eSituation_03 VARCHAR(255),
eTimes_01 smalldatetime,
eTimes_03 smalldatetime,
eTimes_05 smalldatetime,
eTimes_06 smalldatetime,
eTimes_07 smalldatetime,
eTimes_09 smalldatetime,
eTimes_11 smalldatetime,
eTimes_12 smalldatetime,
eTimes_13 smalldatetime,
);

CREATE TABLE PCRMEDCOMPGROUP (
MedicationKey INT FOREIGN KEY REFERENCES FACTPCRMEDICATION(PerKey)
PcrMedCompGroupKey INT NOT NULL PRIMARY KEY,
eMedications_08 VARCHAR(255)
);

CREATE TABLE PCRPATIENTRACEGROUP (
PcrPatientRaceGroupKey INT NOT NULL PRIMARY KEY,
ePatient_14 VARCHAR(255),
);

CREATE TABLE PCRVITALGLASGOWQUALIFIERGROUP (
VitalKey int FOREIGN KEY REFERENCES FACTPCRVITAL(PerKey
),
eVitals_22 VARCHAR(255)
);

CREATE TABLE COMPUTEDELEMENTS (
PerKey INT NOT NULL PRIMARY KEY,
EMSDispatchCenterTimeSec INT,
EMSSceneResponseTimeMin INT,
EMSSceneTimeMin INT,
EMSSceneToPatientTimeMin INT,
EMSSystemResponseTimeMin INT,
EMSTotalCallTimeMin INT,
EMSTransportTimeMin INT,
EMSChuteTimeMin INT,
USCensusDivision VARCHAR(255),
USCensusRegion VARCHAR(255),
Urbanicity VARCHAR(255),
Ageinyear INT,
NasemsoRegion  VARCHAR(255)
);



